// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuajpsrnynudfgmqiqch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1YWpwc3JueW51ZGZnbXFpcWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzkxNDUsImV4cCI6MjA2MzM1NTE0NX0.Ax1BcyqkYd1-VZ5Lu6K4KAJ0CxSmVZmvKW0-ijlfQ9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);